---
title: "Florida School Grades"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggmap)
library(plotly)
library(httr)
library(readxl)
library(janitor)
library(maps)
library(shiny)

```



```{r district_grades, include=FALSE}

url_district <- ("http://www.fldoe.org/core/fileparse.php/18534/urlt/DistrictGrades19.xls")


httr::GET(url_district, write_disk(grades_d <- tempfile(fileext = ".xls")))

district_grades <- read_excel(grades_d, skip =1)

district_grades <- janitor::clean_names(district_grades) %>%
  dplyr::rename(percent_points = percent_of_total_possible_points)



```


```{r get_school_data, include=FALSE}

url_school  <- ("http://www.fldoe.org/core/fileparse.php/18534/urlt/SchoolGrades19.xls")


httr::GET(url_school, write_disk(grades_s <- tempfile(fileext = ".xls")))


school_grades_org <- read_excel(grades_s, skip =4)

school_grades <- janitor::clean_names(school_grades_org)


school_grades <- school_grades %>%
  dplyr::rename(alt_ese = alternative_ese_center_school) %>%
  dplyr::rename(percent_minority = percent_of_minority_students) %>%
  dplyr::rename(percent_econdis = percent_of_economically_disadvantaged_students) %>%dplyr::rename(english_achivement = english_language_arts_achievement) %>%
  dplyr::rename(english_gains = english_language_arts_learning_gains) %>%
  dplyr::rename(english_learning_gains_lowest_25 = english_language_arts_learning_gains_of_the_lowest_25_percent )


school_data <- shiny::reactive({
  school_data <- if(any(input$district == "ALL")){
    school_data <- (school_grades)
  }else{
    dplyr::filter(school_grades, district_name == input$district)
  }
    
  
})


grade_history <- shiny::reactive({
  grade_history <- if(any(input$district_h == "ALL")){
  grade_history <- (school_grades)
}else{
    dplyr::filter(school_grades, district_name == input$district_h)
  }
})


```



```{r florida_base, include=FALSE}

states <- map_data("state")


# Get Florida
fl_df <- subset(states, region == "florida")

# Get Florida county and change name to district name to match district grade key column
counties <- map_data("county")
fl_county <- subset(counties, region == "florida") %>%
  rename("district_name" = "subregion")

# Get Florida object
fl_base <- ggplot(data = fl_df, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")


fl_base + theme_nothing() + 
  geom_polygon(data = fl_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill = NA)  # get the state border back on top


```


```{r data_for_map}

# Change District Case and Names to match Florida Counties 
district_grades$district_name <- tolower(district_grades$district_name)

district_grades$district_name <- gsub("miami-miami-dade", "miami-dade", fixed = TRUE, district_grades$district_name)

district_grades$district_name <- gsub("desoto", "de soto", fixed = TRUE, district_grades$district_name)

district_grades$district_name <- gsub("st. johns", "st johns", fixed = TRUE, district_grades$district_name)

district_grades$district_name <- gsub("st. lucie", "st lucie", fixed = TRUE, district_grades$district_name)


# Create Map Grades 
map_district_grades <- inner_join(fl_county, district_grades, by = "district_name") 
```


```{r create_theme }
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
)
```


```{r create_map}
map_fl_school_grades <- fl_base + 
  geom_polygon(data = map_district_grades, aes(fill = percent_points, label = district_name, label2 = grade_2019), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes



 p <- plotly::ggplotly(map_fl_school_grades)
 
```




Home
====================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Mapped Florida School District Grades

```{r}
p
```

Column {data-width=350}
-----------------------------------------------------------------------

### Data Table

```{r}
district_grades$district_name <- toupper(district_grades$district_name)
DT::datatable(district_grades[,c(2,16,18)], rownames = FALSE)
```




```{r eval = FALSE}

selectInput(inputId = "district",
            label = "Select a School District",
            choices = c(unique(as.character(school_grades$district_name)),
                        "ALL"))


```



```{r eval=FALSE}

checkboxGroupInput(inputId = "select_var", 
                       label = "Select variables", 
                       choices = names(school_data()),
                       selected = names(school_data()))
```




School Grades
====================================================


Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(inputId = "district",
            label = "Select a School District",
            choices = c(unique(as.character(school_grades$district_name)),
                        "ALL"))
```




Column {.tabset}
-----------------------------------------------------------------------

### All School Grades

```{r eval = FALSE}
fillCol(height = 600, flex = c(NA, 1), 
  
    #checkboxGroupInput(inputId = "var", 
                       #label = "Select variables", 
                       #choices = names(school_data()),
                       #selected = names(school_data())),  
    selectInput(inputId = "district",
            label = "Select a School District",
            choices = c(unique(as.character(school_grades$district_name)),
                        "ALL")),

  DT:: DTOutput("school_tbl", input$var,height = "100%")
)

output$school_tbl <- DT::renderDT({
  DT::datatable(school_data(), rownames = FALSE)})

```



```{r eval = FALSE}
checkboxGroupInput(inputId = "var", 
                       label = "Select variables", 
                       choices = names(school_data()),
                       selected = names(school_data()))


checkboxGroupInput(inputId = "select_var", 
                       label = "Select variables", 
                       choices = names(df()),
                       selected = names(df()))
```



```{r eval=TRUE}
  

DT::renderDT({
  DT::datatable(school_data()[,c(4,20, 44:45,47:48)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```


### Elementary Schools

```{r}

  DT::renderDT({
    school_data <- school_data() %>%
  dplyr:: filter(school_type == "01") 
  DT::datatable(school_data[,c(4,20, 44:45,47:48)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
  
```



### Middle Schools 

```{r}
DT::renderDT({
    school_data <- school_data() %>%
  dplyr:: filter(school_type == "02") 
  DT::datatable(school_data[,c(4,20, 44:45,47:48)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
  

```


### High Schools

```{r}
DT::renderDT({
    school_data <- school_data() %>%
  dplyr:: filter(school_type == "03") 
  DT::datatable(school_data[,c(4,20, 44:45,47:48)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
  
```



### English Testing

```{r}
DT::renderDT({
  DT::datatable(school_data()[,c(4:7)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 3,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```

### Math Testing

```{r}
DT::renderDT({
  DT::datatable(school_data()[,c(4, 8:10)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 5,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```


### Science 

```{r}
DT::renderDT({
  DT::datatable(school_data()[,c(4, 11)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```

### Social Studies

```{r}
DT::renderDT({
  DT::datatable(school_data()[,c(4, 12)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```


Grade History
============================================


Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(inputId = "district_h",
            label = "Select a School District",
            choices = c(unique(as.character(school_grades$district_name)),
                        "ALL"))
```


Column {.tabset}
-----------------------------------------------------------------------

### 2015-2019

```{r}
DT::renderDT({
  DT::datatable(grade_history()[,c(4,24,23:20)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```


### 2010-2014

```{r}
DT::renderDT({
  DT::datatable(grade_history()[,c(4,29:25)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})

```

### 2005-2009

```{r}
DT::renderDT({
  DT::datatable(grade_history()[,c(4,34:30)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```

### 1999-2004

```{r}
DT::renderDT({
  DT::datatable(grade_history()[,c(4,40:35)],  rownames = FALSE,
               extensions = "Buttons",
                  options = list(
                    columnDefs = list(list(className = 'dt-right')),
                    pageLength = 10,
                    dom = 'lftripB',
                    buttons = c('copy', 'print', 'csv')))})
```

About
================================================


Column {data-width=650}
-----------------------------------------------------------------------

### About the Application 
```{r}
includeMarkdown("About.md")





```

Column {data-width=300}
---------------------------------------------------------
### Download School Grade Data

```{r eval=TRUE}
downloadLink("downloadData", "Download School Grades Data")



  

  output$downloadData <- downloadHandler(
    filename = function() {
      paste("school-grades-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      write.csv(school_data(), file)
    }
  )
  
  
  
  
```


-------------------------------------------
### Download District Grade Data

```{r}
downloadLink("downloadData_district", "Download District Grades Data")



  

  output$downloadData_district <- downloadHandler(
    filename = function() {
      paste("district-grades-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      write.csv(district_grades, file)
    }
  )
  

```

